### ISSUE TITLE
Problem visualizing spanish translation on github.io

### ISSUE THREAD

**Issue by mt0rm0** [Atcold/pytorch-Deep-Learning#775]
I found an error visualizing on the github.io page the file /docs/es/week02/02-1.md. 

The english version of the file appears before some parts and the layout of the spanish parts after the english parts gets a bit messed up.

![grafik](https://user-images.githubusercontent.com/71704890/116371688-fac12280-a80b-11eb-9f7d-9bc3d70a057c.png)

![grafik](https://user-images.githubusercontent.com/71704890/116371852-26dca380-a80c-11eb-8530-17d3f61bf260.png)

**Comment by Atcold** [comment]
Thanks.

@ritchieng do you think you can fix this?

**Comment by ritchieng** [comment]
Fixed.

https://github.com/Atcold/pytorch-Deep-Learning/commit/efec54c79ddaa570e68c93229f16a149e73dfa35
https://github.com/Atcold/pytorch-Deep-Learning/commit/c376cfde3f843a2a27316579db7d1d024152787c
https://github.com/Atcold/pytorch-Deep-Learning/commit/ef9b9cf271b9e7888230841c0a43558a6d3a3aaa

For any problems regarding such rendering, we'll need a line gap for all commented out code. That's the problem because the code base is a bit messy in terms of line gap consistency.

**Comment by Atcold** [comment]
Thank you @ritchieng for fixing this.
@mt0rm0, plz, confirm resolution of the issue on your end.

**Comment by mt0rm0** [comment]
Problem persisting on paragraphs:

Traditional neural network
Backpropagation through a non-linear function
Backprop through a functional module

**Comment by ritchieng** [comment]
Probably the same problem. Let me fix it.

**Comment by mt0rm0** [comment]
Yep, exactly the same problem. Spacing between blocks needed.

**Comment by ritchieng** [comment]
As expected, fixed.

https://github.com/Atcold/pytorch-Deep-Learning/commit/0760143bb49459feee01996cc35164840a6ea33f

**Comment by mt0rm0** [comment]
Thank you!
